services:
  - type: web
    name: uk-travel-frontend
    env: node
    rootDir: frontend
    nodeVersion: 18.20.2
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://uk-travel-backend.onrender.com/api
